# Generated by Django 2.1.11 on 2020-01-07 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_auto_20200103_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='category',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
