# Generated by Django 2.1.11 on 2020-01-08 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0004_auto_20200108_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='snippets.Category'),
            preserve_default=False,
        ),
    ]
