# Generated by Django 2.1.11 on 2020-01-12 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0005_snippet_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='category_temp',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='snippet',
            name='title_temp',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
