# Generated by Django 2.1.11 on 2020-01-12 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0006_auto_20200112_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snippet',
            name='category_temp',
        ),
        migrations.RemoveField(
            model_name='snippet',
            name='title_temp',
        ),
        migrations.AlterField(
            model_name='snippet',
            name='category',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
